title: Anpeng Wang's Homepage
page-top-title: Anpeng Wang
top-section-bg-text: Robotics Engineering
home-subtitle: Anpeng Wang &ensp;|&ensp;王安鹏
copyright-text: '&copy; Anpeng Wang 2025. All Rights Reserved.'
